### ISSUE TITLE
missing skeletons file

### ISSUE THREAD

**Issue by worthlessFella** [TaeSoo-Kim/TCNActionRecognition#11]
Hi, could you also upload the file

/home-2/jhou16@jhu.edu/data/nturgbd/samples_with_missing_skeletons.txt

This file is missing and not sure how to get it

**Comment by TaeSoo-Kim** [comment]
Please refer to this: https://github.com/shahroudy/NTURGB-D/blob/master/Matlab/samples_with_missing_skeletons.txt
