### ISSUE TITLE
dont understand the process of MEAN SUBTRACTION

### ISSUE THREAD

**Issue by FesianXu** [TaeSoo-Kim/TCNActionRecognition#5]
Hi, kim, i dont really understand the process of MEAN SUBTRACTION in the train.py, especially those codes:
```python
## THIS IS MEAN SUBTRACTION
      x = value.reshape((max_len,feat_dim))
      nonzeros = np.where(np.array([np.sum(x[i])>0 for i in range(0,x.shape[0])])==False)[0] 
      # i dont understand what nonzeros stand for ?
      if len(nonzeros) == 0:
        last_time = 0
      else:
        last_time = nonzeros[0]
      x.setflags(write=1)
      x[:last_time] = x[:last_time] - train_x_mean
```
would you please describe how it work? Thanks

**Comment by TaeSoo-Kim** [comment]
Hi Fesian,

The mean subtraction and max_len are actually related. max_len is the length of the longest sample in the dataset. Note that all samples have variable length. max_len sets all samples to equal length of max_len (I think I set it to 300). 

Then, for example, if you have a sample of length 200, then the time steps 0:200 are filled in with data, and 200:300 are zero-padded. The mean subtraction only subtracts the mean skeleton from 0:200 and leaves the zero padded sequence as is. Does this make sense?

Thanks,
TK

**Comment by FesianXu** [comment]
Appreciate , it does help me !

**Comment by FesianXu** [comment]
Thanks for your answer. Also, in the code
```python
nonzeros = np.where(np.array([np.sum(x[i])>0 for i in range(0,x.shape[0])])==False)[0]
```
so i guess `nonzeros` stands for the index of the padding zeros ? if it is true, then i think you should use '!=' instead of `>`. Is it a bug here?
